Fix challenge depth buffer challenge
The shader.wgsl contains entry point `vs_main` and `fs_main`, but the rust code would reference them `main` and `main`

It would cause the following crash when trying to run the code:
```
[2021-11-25T14:50:43Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    error matching VERTEX shader requirements against the pipeline
    unable to find entry point 'main'
```

This fixes it.